<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Exception Handling &amp; Expensive or Not Python - David&#39;s Blog</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<meta name="author" content="David" /><meta name="description" content="1. Basics concepts Try to understand the exception information (Traceback (most recent call last)) :
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 def foo(): print(10 * (1 / 0)) def main(): foo() if __name__ == &amp;#34;__main__&amp;#34;: main() Traceback (most recent call last): File &amp;#34;main.py&amp;#34;, line 10, in &amp;lt;module&amp;gt; main() File &amp;#34;main.py&amp;#34;, line 6, in main foo() File &amp;#34;main.py&amp;#34;, line 2, in foo print(10 * (1 / 0)) ZeroDivisionError: division by zero As you can see The last line of the error message indicates what happened: print(10 * (1 / 0))." />






<meta name="generator" content="Hugo 0.123.7 with theme even" />


<link rel="canonical" href="https://davidzhu.xyz/post/python/basics/004-exception-handling/" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">



<link href="/sass/main.min.f92fd13721ddf72129410fd8250e73152cc6f2438082b6c0208dc24ee7c13fc4.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">


<meta property="og:title" content="Exception Handling &amp; Expensive or Not Python" />
<meta property="og:description" content="1. Basics concepts Try to understand the exception information (Traceback (most recent call last)) :
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 def foo(): print(10 * (1 / 0)) def main(): foo() if __name__ == &#34;__main__&#34;: main() Traceback (most recent call last): File &#34;main.py&#34;, line 10, in &lt;module&gt; main() File &#34;main.py&#34;, line 6, in main foo() File &#34;main.py&#34;, line 2, in foo print(10 * (1 / 0)) ZeroDivisionError: division by zero As you can see The last line of the error message indicates what happened: print(10 * (1 / 0))." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://davidzhu.xyz/post/python/basics/004-exception-handling/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2023-11-24T09:37:26+00:00" />
<meta property="article:modified_time" content="2023-11-24T09:37:26+00:00" />

<meta itemprop="name" content="Exception Handling &amp; Expensive or Not Python">
<meta itemprop="description" content="1. Basics concepts Try to understand the exception information (Traceback (most recent call last)) :
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 def foo(): print(10 * (1 / 0)) def main(): foo() if __name__ == &#34;__main__&#34;: main() Traceback (most recent call last): File &#34;main.py&#34;, line 10, in &lt;module&gt; main() File &#34;main.py&#34;, line 6, in main foo() File &#34;main.py&#34;, line 2, in foo print(10 * (1 / 0)) ZeroDivisionError: division by zero As you can see The last line of the error message indicates what happened: print(10 * (1 / 0))."><meta itemprop="datePublished" content="2023-11-24T09:37:26+00:00" />
<meta itemprop="dateModified" content="2023-11-24T09:37:26+00:00" />
<meta itemprop="wordCount" content="1211">
<meta itemprop="keywords" content="python," /><meta name="twitter:card" content="summary"/><meta name="twitter:title" content="Exception Handling &amp; Expensive or Not Python"/>
<meta name="twitter:description" content="1. Basics concepts Try to understand the exception information (Traceback (most recent call last)) :
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 def foo(): print(10 * (1 / 0)) def main(): foo() if __name__ == &#34;__main__&#34;: main() Traceback (most recent call last): File &#34;main.py&#34;, line 10, in &lt;module&gt; main() File &#34;main.py&#34;, line 6, in main foo() File &#34;main.py&#34;, line 2, in foo print(10 * (1 / 0)) ZeroDivisionError: division by zero As you can see The last line of the error message indicates what happened: print(10 * (1 / 0))."/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">David&#39;s Blog</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/">
        <li class="mobile-menu-item">Home</li>
      </a><a href="/post/">
        <li class="mobile-menu-item">Archives</li>
      </a><a href="/tags/">
        <li class="mobile-menu-item">Tags</li>
      </a><a href="/categories/">
        <li class="mobile-menu-item">Categories</li>
      </a>
  </ul>

  


</nav>

  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">David&#39;s Blog</a>
</div>





<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/">Home</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/post/">Archives</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/tags/">Tags</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/categories/">Categories</a>
      </li>
  </ul>
</nav>

    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
    
    <header class="post-header">
      <h1 class="post-title">Exception Handling &amp; Expensive or Not Python</h1>

      <div class="post-meta">
        <span class="post-time"> 2023-11-24 </span>
        <div class="post-category">
            <a href="/categories/python/"> python </a>
            </div>
        
      </div>
    </header>

    <div class="post-toc" id="post-toc">
  <h2 class="post-toc-title">Contents</h2>
  <div class="post-toc-content always-active">
    <nav id="TableOfContents">
  <ul>
    <li>
      <ul>
        <li><a href="#1-basics-concepts">1. Basics concepts</a></li>
        <li><a href="#2-types-of-exceptions">2. Types of Exceptions</a></li>
        <li><a href="#3-handle-exceptions">3. Handle Exceptions</a>
          <ul>
            <li><a href="#predefined-clean-up-actions">Predefined clean-up actions</a></li>
          </ul>
        </li>
        <li><a href="#4-performance">4. Performance</a></li>
        <li><a href="#5-when-to-catch">5. When to catch</a>
          <ul>
            <li><a href="#51-at-the-lowest-possible-level">5.1. At the lowest possible level</a></li>
            <li><a href="#52-at-the-highest-possible-level">5.2. At the highest possible level</a></li>
          </ul>
        </li>
        <li><a href="#6-when-to-throw-exceptions">6. When to throw exceptions</a></li>
      </ul>
    </li>
  </ul>
</nav>
  </div>
</div>
    <div class="post-content">
      <h2 id="1-basics-concepts">1. Basics concepts</h2>
<p>Try to understand the exception information (<em>Traceback (most recent call last)</em>) :</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span><span class="lnt">14
</span><span class="lnt">15
</span><span class="lnt">16
</span><span class="lnt">17
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="line"><span class="cl"><span class="k">def</span> <span class="nf">foo</span><span class="p">():</span>
</span></span><span class="line"><span class="cl">    <span class="nb">print</span><span class="p">(</span><span class="mi">10</span> <span class="o">*</span> <span class="p">(</span><span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span><span class="p">))</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">def</span> <span class="nf">main</span><span class="p">():</span>
</span></span><span class="line"><span class="cl">    <span class="n">foo</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">if</span> <span class="vm">__name__</span> <span class="o">==</span> <span class="s2">&#34;__main__&#34;</span><span class="p">:</span>
</span></span><span class="line"><span class="cl">    <span class="n">main</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
</span></span><span class="line"><span class="cl">  <span class="n">File</span> <span class="s2">&#34;main.py&#34;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">10</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
</span></span><span class="line"><span class="cl">    <span class="n">main</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">  <span class="n">File</span> <span class="s2">&#34;main.py&#34;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">6</span><span class="p">,</span> <span class="ow">in</span> <span class="n">main</span>
</span></span><span class="line"><span class="cl">    <span class="n">foo</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">  <span class="n">File</span> <span class="s2">&#34;main.py&#34;</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">foo</span>
</span></span><span class="line"><span class="cl">    <span class="nb">print</span><span class="p">(</span><span class="mi">10</span> <span class="o">*</span> <span class="p">(</span><span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span><span class="p">))</span>
</span></span><span class="line"><span class="cl"><span class="ne">ZeroDivisionError</span><span class="p">:</span> <span class="n">division</span> <span class="n">by</span> <span class="n">zero</span>
</span></span></code></pre></td></tr></table>
</div>
</div><p>As you can see The last line of the error message indicates what happened: <code>print(10 * (1 / 0))</code>.</p>
<blockquote>
<p>Errors detected during execution are called <em>exceptions</em>. <a href="https://docs.python.org/3/tutorial/errors.html">Errors and Exceptions — Python 3.12.0</a></p>
</blockquote>
<h2 id="2-types-of-exceptions">2. Types of Exceptions</h2>
<p><code>BaseException</code> is the common base class of all exceptions. One of its subclasses, <code>Exception</code>, is the base class of all the <strong>non-fatal</strong> exceptions. Exceptions which are not subclasses of <code>Exception</code> are not typically handled, because they are used to indicate that the program should terminate. They include <code>SystemExit</code>which is raised by <code>sys.exit()</code> and <code>KeyboardInterrupt</code>which is raised when a user wishes to interrupt the program.</p>
<p><code>Exception</code>can be used as a wildcard that catches (almost) everything. However, it is good practice to be as specific as possible with the types of exceptions that we intend to handle, and to allow any unexpected exceptions to propagate on.</p>
<h2 id="3-handle-exceptions">3. Handle Exceptions</h2>
<p>The most common pattern for handling <code>Exception</code> is to <strong>print or log the exception and then re-raise it</strong> (allowing a caller to handle the exception as well):</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="line"><span class="cl"><span class="kn">import</span> <span class="nn">sys</span>
</span></span><span class="line"><span class="cl">
</span></span><span class="line"><span class="cl"><span class="k">try</span><span class="p">:</span>
</span></span><span class="line"><span class="cl">    <span class="n">f</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s1">&#39;myfile.txt&#39;</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">    <span class="n">s</span> <span class="o">=</span> <span class="n">f</span><span class="o">.</span><span class="n">readline</span><span class="p">()</span>
</span></span><span class="line"><span class="cl">    <span class="n">i</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">s</span><span class="o">.</span><span class="n">strip</span><span class="p">())</span>
</span></span><span class="line"><span class="cl"><span class="k">except</span> <span class="ne">OSError</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
</span></span><span class="line"><span class="cl">    <span class="nb">print</span><span class="p">(</span><span class="s2">&#34;OS error:&#34;</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">    <span class="k">raise</span>
</span></span><span class="line"><span class="cl"><span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
</span></span><span class="line"><span class="cl">    <span class="nb">print</span><span class="p">(</span><span class="sa">f</span><span class="s2">&#34;Unexpected </span><span class="si">{</span><span class="n">err</span><span class="si">=}</span><span class="s2">, </span><span class="si">{</span><span class="nb">type</span><span class="p">(</span><span class="n">err</span><span class="p">)</span><span class="si">=}</span><span class="s2">&#34;</span><span class="p">)</span>
</span></span><span class="line"><span class="cl">    <span class="k">raise</span>
</span></span></code></pre></td></tr></table>
</div>
</div><h3 id="predefined-clean-up-actions">Predefined clean-up actions</h3>
<p>Some objects define standard clean-up actions to be undertaken when the object is no longer needed, regardless of whether or not the operation using the object succeeded or failed. Look at the following example, which tries to open a file and print its contents to the screen.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="line"><span class="cl"><span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&#34;myfile.txt&#34;</span><span class="p">):</span>
</span></span><span class="line"><span class="cl">    <span class="nb">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&#34;&#34;</span><span class="p">)</span>
</span></span></code></pre></td></tr></table>
</div>
</div><p>The problem with this code is that it leaves the file open for an indeterminate amount of time after this part of the code has finished executing. This is not an issue in simple scripts, but can be a problem for larger applications. The <a href="https://docs.python.org/3/reference/compound_stmts.html#with"><code>with</code></a> statement allows objects like files to be used in a way that ensures they are always cleaned up promptly and correctly.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre tabindex="0" class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span></code></pre></td>
<td class="lntd">
<pre tabindex="0" class="chroma"><code class="language-python" data-lang="python"><span class="line"><span class="cl"><span class="k">with</span> <span class="nb">open</span><span class="p">(</span><span class="s2">&#34;myfile.txt&#34;</span><span class="p">)</span> <span class="k">as</span> <span class="n">f</span><span class="p">:</span>
</span></span><span class="line"><span class="cl">    <span class="k">for</span> <span class="n">line</span> <span class="ow">in</span> <span class="n">f</span><span class="p">:</span>
</span></span><span class="line"><span class="cl">        <span class="nb">print</span><span class="p">(</span><span class="n">line</span><span class="p">,</span> <span class="n">end</span><span class="o">=</span><span class="s2">&#34;&#34;</span><span class="p">)</span>
</span></span></code></pre></td></tr></table>
</div>
</div><p>After the statement is executed, the file <em>f</em> is always closed, <strong>even if a problem was encountered while processing the lines</strong>. Objects which, like files, provide predefined clean-up actions will indicate this in their documentation.</p>
<h2 id="4-performance">4. Performance</h2>
<p><a href="https://stackoverflow.com/questions/66536614/how-is-exception-handling-implemented-in-python">performance - How is exception handling implemented in Python? - Stack Overflow</a>:</p>
<blockquote>
<p>I&rsquo;ve learned from other SO answers that a try/catch block is <a href="https://stackoverflow.com/a/2522013/1663614">cheaper than an if/else statement</a> if the exception is expected to be raised rarely, and that <a href="https://stackoverflow.com/a/36784706/1663614">it&rsquo;s the call depth that&rsquo;s important</a> because filling the stacktrace is expensive. This is probably principally true for all programming languages.</p>
</blockquote>
<blockquote>
<p>If you throw an exception, all functions will be exited back to the point where it finds a <code>try...catch</code> block with a matching <code>catch</code> type. If your function isn&rsquo;t called from within a try block, the program will exit with an unhandled exception.</p>
</blockquote>
<p>Find some discussions, from: <a href="https://stackoverflow.com/questions/1308432/do-try-catch-blocks-hurt-performance-when-exceptions-are-not-thrown?noredirect=1&amp;lq=1">c# - Do try/catch blocks hurt performance when exceptions are not thrown? - Stack Overflow</a></p>
<blockquote>
<p>During a code review with a Microsoft employee we came across a large section of code inside a <code>try{}</code> block. She and an IT representative suggested this can have effects on performance of the code. In fact, they suggested most of the code should be outside of try/catch blocks, and that only important sections should be checked. The Microsoft employee added and said an upcoming white paper warns against incorrect try/catch blocks.</p>
</blockquote>
<blockquote>
<p>try catch blocks have a negligible impact on performance but exception Throwing can be pretty sizable, this is probably where your coworker was confused.</p>
</blockquote>
<p>Another disscussion: <a href="https://stackoverflow.com/questions/16451777/is-it-expensive-to-use-try-catch-blocks-even-if-an-exception-is-never-thrown?noredirect=1&amp;lq=1">java - Is it expensive to use try-catch blocks even if an exception is never thrown? - Stack Overflow</a></p>
<blockquote>
<p><code>try</code> has almost no expense at all. Instead of doing the work of setting up the <code>try</code> at runtime, the code&rsquo;s metadata is structured at compile time such that when an exception is thrown, it now does a relatively expensive operation of walking up the stack and seeing if any <code>try</code> blocks exist that would catch this exception. From a layman&rsquo;s perspective, <code>try</code> may as well be free. It&rsquo;s actually throwing the exception that costs you - but unless you&rsquo;re throwing hundreds or thousands of exceptions, you still won&rsquo;t notice the cost.</p>
</blockquote>
<p>Another post: <a href="https://stackoverflow.com/questions/299068/what-are-the-effects-of-exceptions-on-performance-in-java?noredirect=1&amp;lq=1">What are the effects of exceptions on performance in Java? - Stack Overflow</a></p>
<blockquote>
<p>In Java much of the expense of throwing an exception is the time spent gathering the stack trace, which occurs when the exception object is created. The actual cost of throwing the exception, while large, is considerably less than the cost of creating the exception.</p>
<p><a href="https://stackoverflow.com/a/8024032/16317008">https://stackoverflow.com/a/8024032/16317008</a></p>
</blockquote>
<h2 id="5-when-to-catch">5. When to catch</h2>
<h3 id="51-at-the-lowest-possible-level">5.1. At the lowest possible level</h3>
<p>This is the level at which you are integrating with third party code, such as an ORM tool or any library performing IO operations (accessing resources over HTTP, reading a file, saving to the database, you name it). That is, <strong>the level at which you leave your application’s native code</strong> to interact with other components.</p>
<p>The guidelines in this scenario are:</p>
<ul>
<li><strong>Handle only specific exceptions</strong>, such as <code>SqlTimeoutException</code> or <code>IOException</code>. Never handle a generic exception (of type <code>Exception</code>)</li>
<li><strong>Handle it only if you have something meaningful to do about it</strong>, such as retries, triggering compensatory actions, or adding more data to the exception (e.g. context variables), and then re-throw it</li>
<li><strong>Do not perform logging here</strong></li>
<li><strong>Let all other exceptions bubble up</strong> as they will be handled by the second case</li>
</ul>
<h3 id="52-at-the-highest-possible-level">5.2. At the highest possible level</h3>
<p>This would be the last place where you can handle the exception before it is thrown directly to the user.</p>
<p>Your goal here is to <strong>log the error and forward the details to the programmers</strong> so they can identify and correct the error. Add as much information as possible, record it, and then <strong>show an apology message to the user</strong>, as there’s probably nothing they can do about it, especially if it is a bug in the software.</p>
<p>The guidelines in this second scenario are:</p>
<ul>
<li>Handle the generic Exception class</li>
<li>Add more information from current execution context</li>
<li>Log the error and notify the programmers</li>
<li>Show an apology to the user</li>
<li>Work it out as soon as you can</li>
</ul>
<p>Learn more, very good explanation: <a href="https://stackoverflow.com/a/59511485">https://stackoverflow.com/a/59511485</a></p>
<h2 id="6-when-to-throw-exceptions">6. When to throw exceptions</h2>
<p>Easier to explain in the context of developing a library. <strong>You should throw when you reached an error and there&rsquo;s nothing more you can do</strong> besides letting the consumer of your APIs know about it, and letting them decide.</p>
<p>Imagine you&rsquo;re the developer of some data access library. When you reach a network error, there&rsquo;s nothing you can do besides throwing an exception. That&rsquo;s an irreversible error from a data access library standpoint.</p>
<p>Learn more, very good explanation: <a href="https://stackoverflow.com/a/59511485">https://stackoverflow.com/a/59511485</a></p>

    </div>

    <div class="post-copyright">
  <p class="copyright-item">
    <span class="item-title">Author</span>
    <span class="item-content">David</span>
  </p>
  <p class="copyright-item">
    <span class="item-title">LastMod</span>
    <span class="item-content">
        2023-11-24
        
    </span>
  </p>
  
  
</div>
<footer class="post-footer">
      <div class="post-tags">
          <a href="/tags/python/">python</a>
          </div>
      <nav class="post-nav">
        <a class="prev" href="/post/js/crawler/001-basic-concepts/">
            <i class="iconfont icon-left"></i>
            <span class="prev-text nav-default">Basic Concepts</span>
            <span class="prev-text nav-mobile">Prev</span>
          </a>
        <a class="next" href="/post/python/basics/003-yield-generator/">
            <span class="next-text nav-default">Yeild &amp; Generator Python</span>
            <span class="next-text nav-mobile">Next</span>
            <i class="iconfont icon-right"></i>
          </a>
      </nav>
    </footer>
  </article>
        </div>
        

  

  

      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
      <a href="mailto:shwezhu@qq.com" class="iconfont icon-email" title="email"></a>
      <a href="https://github.com/shwezhu" class="iconfont icon-github" title="github"></a>
  <a href="https://davidzhu.xyz/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme - 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    2023 - 
    2024<span class="heart"><i class="iconfont icon-heart"></i></span><span>David</span>
  </span>
</div>

    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>



<script type="text/javascript" src="/js/main.min.4ae89da218555efa0e7093a20b92017d2e1202b66fff9fc2edf4cb8d44b44c6e.js"></script>








</body>
</html>
